import './globals.css'
import { Inter } from 'next/font/google'
import ProviderWrapper from './providerWrapper'
import Header from './components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
        
          <body className={inter.className}>
          <ProviderWrapper>
            <Header />
              {children}
          </ProviderWrapper>
          </body>

      
    </html>
  )
}
